### PR TITLE
WIP: Module install fix

### PR DESCRIPTION
**Pull request by zbeekman**
This should do the trick...

### CODE REVIEW

**Comment by zbeekman** [comment]
@porteri This PR should be ready to merge.

**Comment by porteri** [comment]
@zbeekman I just saw your comment. I opened a PR against your branch `module-install-fix` from `nrc-fuels/vtkmofo` `master` branch to bring in the latest fixes so that your PR will have those coming into this repo.  Ping me when you have merged and want me to approve this PR (or maybe you want to rebase your branch on `nrc-fuels/vtkmofo`? Whatever you think is best.

**Comment by zbeekman** [comment]
@porteri This is ready to ship

**Review by porteri — APPROVED** [review]
LGTM

**Pull request merged**
